/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.models.V1Pod;
import io.kubernetes.client.openapi.models.V1PodList;
import java.io.IOException;

import api.k8s.PodCrud;

public class TestApi {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, ApiException {
        System.out.println(new TestApi().getGreeting());
        String namespace = "";
        V1PodList podList = PodCrud.getPodList(namespace);

        System.out.println("----------- [ Head of pod-list ] -----------");
        for (V1Pod item : podList.getItems()) {
            System.out.println(item.getMetadata().getName());
        }
        System.out.println("----------- [ Tail of pod-list ] -----------");
    }
}
